name: Auto approve and merge PRs by dependabot

# Trigger the workflow on pull request
on:
  pull_request

jobs:
  autoapprove:
    name: Auto Approve a PR by dependabot # Name of the job
    runs-on: ubuntu-latest # Environment on which the job runs
    steps:
      - name: Auto approve
        uses: hmarr/auto-approve-action@v2.0.0
        if: github.actor == 'dependabot[bot]' || github.actor == 'dependabot-preview[bot]'
        with:
          github-token: ${{ secrets.PAT }}
  automerge:
    name: Auto merge after successful checks
    needs: autoapprove
    runs-on: ubuntu-latest
    steps:
      - name: Auto merge
        uses: pascalgn/automerge-action@v0.14.3
        if: github.actor == 'dependabot[bot]' || github.actor == 'dependabot-preview[bot]'
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
          MERGE_LABELS: dependencies
          MERGE_METHOD: rebase